import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#EEEEEE]">
          {/* Container is the global padding for edges of the page*/}

      <body className="container mx-auto px-4 md:px-8 lg:px-16">{children}</body>
    </html>
  );
}
